#pragma once

enum BlockTypes
{
	ENUM_NONE,
	ENUM_TERRAIN_PLATFORM_LEFT = 'a',
	ENUM_TERRAIN_PLATFORM_CENTER,
	ENUM_TERRAIN_PLATFROM_RIGHT,

	ENUM_TERRAIN_TOP_LEFT,
	ENUM_TERRAIN_TOP_CENTER,
	ENUM_TERRAIN_TOP_RIGHT,

	ENUM_TERRAIN_BOTTOM_LEFT,
	ENUM_TERRAIN_BOTTOM_CENTER,
	ENUM_TERRAIN_BOTTOM_RIGHT,

	ENUM_TERRAIN_CENTER_LEFT,
	ENUM_TERRAIN_CENTER,
	ENUM_TERRAIN_CENTER_RIGHT
};
