#pragma once

enum BlockTypes
{
	ENUM_NONE,
	//ENUM_GRASS,
	//ENUM_DIRT,
	//ENUM_GRASS_ULDR,
	//ENUM_GRASS_DLTR,
	//ENUM_STONE,
	//ENUM_DIRT_DLTR,
	//ENUM_DIRT_TLDR,

	ENUM_TERRAIN_PLATFORM_LEFT,
	ENUM_TERRAIN_PLATFORM_CENTER,
	ENUM_TERRAIN_PLATFROM_RIGHT,
	ENUM_TERRAIN_TOP_LEFT,
	ENUM_TERRAIN_TOP_CENTER,
	ENUM_TERRAIN_TOP_RIGHT,
};
